---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: { $.chart.Release.name }
  namespace: "default"
  labels:
    app: "fibonacci-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "fibonacci-app"
  template:
    metadata:
      labels:
        app: "fibonacci-app"
    spec:
      containers:
      - name: "fibonacci-app"
        image: "jfabdo/fibonacci-app:latest"
        env:
        - name: APP_VERSION
          value: "fibonacci-app"
        - name: USER
          value: "fibonacci-app"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "fibonacci-app-hpa-dgrg"
  namespace: "default"
  labels:
    app: "fibonacci-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "fibonacci-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "fibonacci-app-service"
  namespace: "default"
  labels:
    app: "fibonacci-app"
spec:
  ports:
  - protocol: "TCP"
    port: 9001
    targetPort: 8080
  selector:
    app: "fibonacci-app"
  type: "NodePort"
---
