---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fibonacci-app"
  namespace: "default"
  labels:
    app: "{{ .Chart.metadata.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.metadata.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.metadata.name }}"
    spec:
      containers:
      - name: "sample-app"
        image: "jfabdo/{{ .Chart.metadata.name }}:latest"
        env:
        - name: APP_VERSION
          value: "{{ .Chart.Version }}"
        - name: USER
          value: "{{ .Values.user }}"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "{{ .Chart.metadata.name }}-hpa-dgrg"
  namespace: "default"
  labels:
    app: "{{ .Chart.metadata.name }}"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "{{ .Chart.metadata.name }}"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Chart.metadata.name }}-service"
  namespace: "default"
  labels:
    app: "{{ .Chart.metadata.name }}"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "{{ .Chart.metadata.name }}"
  type: "NodePort"
