apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sample-app"
  namespace: "default"
  labels:
    app: "sample-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sample-app"
  template:
    metadata:
      labels:
        app: "sample-app"
    spec:
      containers:
      - name: "sample-app"
        image: "pauloiza/sample-app:latest"
        env:
        - name: APP_VERSION
          value: "{{ .Chart.Version }}"
        - name: USER
          value: "{{ .Values.user }}"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "fibonacci-app-hpa-dgrg"
  namespace: "default"
  labels:
    app: "fibonacci-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "fibonacci-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sample-app-service"
  namespace: "default"
  labels:
    app: "sample-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "sample-app"
  type: "NodePort"
