---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ .Values.app-name }}
  namespace: default
  labels:
    app: {{ .Values.app-name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app-name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app-name }}
    spec:
      containers:
      - name: {{ .Values.app-name }}
        image: jfabdo/{{ .Values.app-name }}:latest
        env:
        - name: APP_VERSION
          value: {{ .Values.app-name }}
        - name: USER
          value: {{ .Values.app-name }}
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: {{ .Values.app-name }}-hpa-dgrg
  namespace: default
  labels:
    app: {{ .Values.app-name }}
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "{{ .Values.app-name }}"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Values.app-name }}-service"
  namespace: "default"
  labels:
    app: "{{ .Values.app-name }}"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "{{ .Values.app-name }}"
  type: "NodePort"
