apiVersion: "apps/v2"
kind: "Deployment"
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "jfabdo/fibonacci-app:latest"
        env:
        - name: APP_VERSION
          value: "{{ .Chart.Version }}"
        - name: USER
          value: "{{ .Values.user }}"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sample-app-hpa-dgrg"
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: {{ .Release.Name }}
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v2"
kind: "Service"
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}
  type: "NodePort"
