---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Values.appname }}-service"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appname }}"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 9001
  selector:
    app: "{{ .Values.appname }}"
  type: "NodePort"
